services:
  vector_db:
    image: pgvector/pgvector:pg14
    container_name: poc_rh_vector
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: rh_poc
    ports:
      - "5433:5432"
    volumes:
      # Aqui está a mágica: isso salva os dados do banco no seu HD
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
    name: rh_poc_pgvector_data